// <auto-generated />
using CoffeeBillboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeBillboard2.Migrations
{
    [DbContext(typeof(CoffeeDBContext))]
    [Migration("20230323093651_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("CoffeeBillboard.Models.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoffeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CoffeePrice")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coffee");
                });
#pragma warning restore 612, 618
        }
    }
}
